#!/bin/sh

set -e

BASEDIR="$HOME/.dotfiles"
DOTBOT_BIN="bin/dotbot"
DOTBOT_DIR="vendor/dotbot"

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"


cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

for conf in ${DEFAULT_CONFIG_PREFIX} "${@}"; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}"
done