# tmuxp
# SESSION CONFIGURATION
# =====================
# Every configuration is required to have:
# - session_name
# - list of windows
# - list of panes for every window in windows
session_name: "default"
start_directory: "~/"
# shell_command_before: "echo hello"
# before_script: "before_script.sh"
# environment:
#   EDITOR: /usr/bin/vim
#   HOME: /tmp/hm
windows:
- window_name: "default"
  focus: true
  # shell_command_before: echo hello
  options:
    automatic-rename: on
  layout: even-horizontal # even-vertical, main-horizontal, main-vertical, or tiled.
  panes:
  # - shell_command: echo hello
  - focus: true
  - #
- panes:
  - shell_command: sudo htop