# "brew tap"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"

# package control
brew "mas"

# dev, python & numerical computing packages
brew "act"
brew "apache-arrow"
brew "cmake"
brew "cython"
brew "gcc"
brew "libomp"
brew "node"
brew "numpy"
brew "openblas"
brew "pipx"
brew "python"
brew "rust"
brew "scipy"

# utils
brew "awscli"
brew "bandwhich"
brew "bat"
brew "blueutil"
# TODO: unable to replace docker desktop until compose v2 supports the AWS ECS integration
# brew "colima"
brew "coreutils"
brew "ctop"
brew "dive"
# TODO: Relaplaced by cask until colima can deal with compose
# brew "docker"
brew "dsq"
brew "dust"
brew "dvc"
brew "exa"
brew "fd"
brew "figlet"
brew "fzf"
brew "gdrive"
brew "gh"
brew "ghostscript"
brew "gifsicle"
brew "git-delta"
brew "git"
brew "git-lfs"
brew "gopass"
brew "htop"
brew "jo"
brew "jq"
brew "lazydocker"
brew "libgit2"
brew "mcfly"
brew "mpv"
brew "mtr"
brew "multimarkdown"
brew "neovim"
brew "pandoc"
brew "pinentry-mac"
brew "procs"
brew "ripgrep"
brew "rsync"
brew "sd"
brew "shellcheck"
brew "shfmt"
brew "sleepwatcher"
brew "starship"
brew "subversion"
brew "tig"
brew "watch"
brew "wget"
brew "yq"

# cask utils
cask "agenda"
cask "alfred"
cask "appcleaner"
cask "caffeine"
cask "dropbox"
cask "firefox-beta"
cask "google-drive"
cask "gpg-suite"
cask "iterm2-beta"
cask "itsycal"
cask "lastpass"
cask "mactex"
cask "spotify"
cask "textbuddy"

# cask comms
cask "discord"
cask "element"
cask "obs"
cask "signal"
cask "slack"
cask "twobird"
cask "zoom"

# cask dev
cask "docker"
cask "insomnia"
cask "mambaforge"
cask "sublime-merge"
cask "sublime-text"
cask "the-unarchiver"
cask "visual-studio-code-insiders"
cask "visual-studio-code"

# cask fonts
cask "font-fira-code"
cask "font-input"
cask "font-iosevka-nerd-font"
cask "font-iosevka"
cask "font-open-sans"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"

# mas utils
mas "iA Writer", id: 775737590
mas "Magnet", id: 441258766
mas "LanguageTool", id: 1534275760

# mas apple
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
