root:
  askformore: false
  autoclip: false
  autoimport: true
  autosync: false
  cliptimeout: 45
  editrecipients: false
  nocolor: false
  noconfirm: true
  nopager: false
  path: gpgcli-gitcli-fs+file://~/.password-store
  safecontent: true
  usesymbols: false
  notifications: false
mounts: {}
