root:
  askformore: false
  autoimport: true
  autosync: false
  cliptimeout: 45
  noconfirm: true
  nopager: false
  path: ~/.password-store
  safecontent: true
  usesymbols: false
  nocolor: false
mounts: {}
